### ISSUE TITLE
Support live turn streaming.

### ISSUE THREAD

**Issue by DanielVF** [DanielVF/Planet-Wars-Canvas-Visualizer#14]

**Comment by javache** [comment]
I've been thinking about this as well, would be very awesome!

What technology should we use for this? 
What will need to change to the data-structures in the javascript (we use the total count of moves quite often)
At the current playback speed we go faster than the bots, I think. This would have to be changed too.

**Comment by DanielVF** [comment]
I think this is fairly simple. We just need a method that can be called to add a new turn of data. If the visualizer is currently paused on the now next to last frame, it also presses play.

**Comment by DanielVF** [comment]
[Closed, this project has been superseded]
